### ISSUE TITLE
Missing Dependency (OpenWRT)

### ISSUE THREAD

**Issue by ChthonVII** [cvmiller/v6brouter#12]
kmod-br-netfilter must be installed. Otherwise the call to sysctl on line 276 of v6brouter_openwrt.sh spits the following error, and the ip6 firewall does not function: "sysctl: error: 'net.bridge.bridge-nf-call-ip6tables' is an unknown key."

While I'm here, I have a number of questions about the firewall functionality (please feel free to split these off into a separate issue if you like):
1. Is my understanding correct that the IPv4 firewall is untouched (i.e., any existing IPv4 iptables rules will continue to be enforced)?
2. Which ip6tables chains stop functioning? (I'd think that existing rules for INPUT and OUTPUT in ip6tables would continue to be enforced, but everything in FORWARD stops functioning and needs to be replaced with something in the new forwarding_rule chain. Is that right?)
3. What's the point of the default rule allowing external SSH? If I understand correctly, that allows someone out in WAN world to initiate a SSH connection to a machine on your local network. Why would you want that?
4. Could you elaborate further on the statement "When in v6brouter mode, it is possible to log into the OpenWRT router via ssh from the outside network. You may wish to add an IPv6 firewall rule to prevent this."? What rule specifically? Also, could you explain how this becomes possible?
5. Is there an inverse of "ebtables -A FORWARD -p ipv6 -i $WAN_DEV -j mark --set-mark 16 --mark-target CONTINUE" that could be used to filter outgoing traffic?
6. Where should new rules be added? Into the script itself?
7. Could you give example rules for the following cases:
7.i. Drop packets bound for destination ports X, Y, Z on LAN machines, regardless of source.
7.ii. Drop all packets in both directions between WAN and LAN machine with IP X.
7.iii. Drop all packets in both directions between WAN and LAN machine with MAC X.

**Comment by ChthonVII** [comment]
One more firewall question:
8. If I understand correctly, the -i parameter for ip6tables is now useless since everything appears to come from br-lan. But what about the -o parameter?

**Comment by cvmiller** [comment]
In my testing kmod-br-netfilter was installed by the package manager as a dependency of ebtables. But I can add it to the Documentation.

**Comment by cvmiller** [comment]
Answering your other questions:

1. Yes, IPv4 uses iptables, which is separate from IPv4.
2. Any ip6tables which rely on -i and -o will be non-functional, since all packets will "appear" to come from the br-lan interface with no exit interface when in bridge-mode.
3. The script inserted rule to allow external SSH is both an example of how to allow external access, and it is quite common to provide external SSH as a management access. Remember that the outside person must still know the IPv6 address of the internal host. If you don't advertise the host, via DNS, it is extremely difficult to sweep a /64. The rule can be commented out in the script if you don't want to provide external SSH access.
4. Blocking external SSH (in answer 3) will prevent external SSH access to the router as well. In briding-mode, the router is just another host on the bridged IPv6 /64.
5. Yes, you could also block outgoing traffic as well. In briding-mode it takes 2 rules, one ebtables to mark the outgoing packet, and one to ip6tables rule to drop it. For example, to drop outbound SSH, do something like the following:
```
ebtables -A FORWARD -p ipv6 -i $LAN_DEV -j mark --set-mark 8 --mark-target CONTINUE
ip6tables -A forwarding_rule -m mark --mark 8 -p tcp --dport 22  -j DROP
```

6. Yes, IPv6 FW rules should be entered directly into the script itself, as the OpenWrt firewall rules set knows nothing of bridging-mode.
7. The ip6tables  rules look exactly like "normal" ip6ables rules with the addition of the --mark parameter. It is the --mark that replaces the -i or -o parameter indicating which interface the traffic arrived. If in the example from #5 above, external packets are marked with 16 and LAN packets are marked with 8, then it is easy to create rules which  drop internal or external traffic. 
7i. 
```
ip6tables -A forwarding_rule -m mark --mark 16 -p tcp --dport X  -j DROP
ip6tables -A forwarding_rule -m mark --mark 16 -p tcp --dport Y  -j DROP
ip6tables -A forwarding_rule -m mark --mark 16 -p tcp --dport Z  -j DROP
```
7ii
```
ip6tables -A forwarding_rule -m mark --mark 16  --dst $BADHOST  -j DROP
ip6tables -A forwarding_rule -m mark --mark 8  --src $BADHOST  -j DROP
```
7iii. You can do this in ebtables, but since MAC addresses are easy to spoof/change, there is little value in doing so. But here's the example:
```
ebtables -A FORWARD -p IPv4  -s ! 00:11:22:33:44:55 -j DROP
```
8. See answer 2. You must use --mark rather than -i and -o when in bridging-mode.

**Comment by cvmiller** [comment]
Updated README.md with dependency. Closing issue.
